# Generated by Django 4.1.1 on 2022-10-05 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='custom_tag',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='title_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
