# Generated by Django 4.1.1 on 2022-10-05 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_project', '0002_project_custom_tag_alter_project_title_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='custom_tag',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='project',
            name='title_image',
            field=models.ImageField(blank=True, upload_to='search_project/project/%Y/%m/%d'),
        ),
    ]
